spring:
  application:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/coupon_finder?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.google.couponfinder.entity, com.google.couponfinder.dto

mini:
  appid: wxfb9f6a157d4f2458
  appsecret: 37a056dbf465b9ed3b202c998722feec
  merchantSecret: 123456

jwt:
  tokenHeader: Authorization
  tokenHead: 'Bearer '
  secret: bingbingbing
  expiration: 1800000

qiniu:
  accessKey: VjqyGJIWeKMORqLsJR-3CMSBiKTxYF25wC5CSPbc
  secretKey: adec1oMqUWZAUKPruXLwus2822HK9wMJwpTllO8J
  bucketName: coupon-finder-images
  path: rsa5pzqlo.hn-bkt.clouddn.com