spring:
  application:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/coupon_finder?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.google.couponfinder.entity