spring:
  application:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/coupon_finder?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: 123456

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.google.couponfinder.entity, com.google.couponfinder.dto

mini:
  appid: wxfb9f6a157d4f2458
  appsecret: 37a056dbf465b9ed3b202c998722feec
  merchantSecret: 123456

jwt:
  tokenHeader: Authorization
  tokenHead: 'Bearer '
  secret: bingbingbing
  expiration: 1800000

qiniu:
  accessKey: VjqyGJIWeKMORqLsJR-3CMSBiKTxYF25wC5CSPbc
  secretKey: adec1oMqUWZAUKPruXLwus2822HK9wMJwpTllO8J
  bucketName: coupon-finder-images-backup1
  path: rtxlr46aj.hn-bkt.clouddn.com

#server:
#    port: 443
#    ssl:
#      key-store-password: mdex375t    #填写pfx-password.txt文件内的密码。
#      key-store-type: JKS
#      key-store: classpath:9876332_shuobin.tech.jks    #您需要使用实际的证书名称替换domain_name.pfx。
